services:
  tabby:
    image: registry.tabbyml.com/tabbyml/tabby
    command: >
      serve --model StarCoder-1B --device cuda --chat-model Qwen2-1.5B-Instruct
    ports:
      - "127.0.0.1:9080:8080"
    volumes:
      - tabby:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  tabby:

  